# Generated by Django 3.2.5 on 2021-07-04 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rolodex_app', '0002_auto_20210703_0341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='state',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='title',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='zipcode',
        ),
    ]
